.\" ============================================================================
.TH ECHO 1
.\" ============================================================================
.SH NAME
echo \(em echo arguments to output
.\" ============================================================================
.SH SYNOPSIS
.B echo
.RI [ argument ...]
.\" ============================================================================
.SH DESCRIPTION
.B echo
copies its command line arguments to its output as a line of text with one space
between each argument.
If there are no arguments, no output is produced.
.\" ============================================================================
.SH EXAMPLE
To see if your system is alive:
.RS 4
.nf

.B echo hello world!
hello world!
.fi
.RE
.\" ============================================================================
