.\" ====================================================================
.TH CHARCOUNT 1
.\" ====================================================================
.SH NAME
charcount \(em count characters in input
.\" ====================================================================
.SH SYNOPSIS
.B charcount
.\" ====================================================================
.SH DESCRIPTION
.B charcount
counts the characters in its input and writes the total as a single line of text to the output.
Since each line of text is internally delimited by a
.B NEWLINE
character, the total count is the number of lines plus the number of characters within each line.
.\" ====================================================================
.SH EXAMPLE
.RS 4
.nf
.B charcount
.B A single line of input.
.B <ENDFILE>
24
.fi
.RE
.\" ====================================================================
