.\" ============================================================================
.TH COPY 1
.\" ============================================================================
.SH NAME
copy \(em copy input to output
.\" ============================================================================
.SH SYNOPSIS
.B copy
.\" ============================================================================
.SH DESCRIPTION
.B copy
copies its input to its output unchanged.
It is useful for copying from a terminal to a file, from file to file, or even
from terminal to terminal.
It may be used for displaying the contents of a file, without interpretation or
formatting, by copying from a file to terminal.
.\" ============================================================================
.SH EXAMPLE
To echo lines typed at your terminal:
.RS 4
.nf

.B copy
.B hello there, are you listening?
hello there, are you listening?
.B yes, I am.
yes, I am.
.B <ENDFILE>
.fi
.RE
.\" ============================================================================
