.\" ============================================================================
.TH LINECOUNT 1
.\" ============================================================================
.SH NAME
linecount \(em count lines in input
.\" ============================================================================
.SH SYNOPSIS
.B linecount
.\" ============================================================================
.SH DESCRIPTION
.B linecount
counts the lines in its input and writes the total as a line of text to the
output.
.\" ============================================================================
.SH EXAMPLE
.RS 4
.nf
.B linecount
.B A single line of input.
.B <ENDFILE>
1
.fi
.RE
.\" ============================================================================
