.\" ============================================================================
.TH WORDCOUNT 1
.\" ============================================================================
.SH NAME
wordcount \(em count words in input
.\" ============================================================================
.SH SYNOPSIS
.B wordcount
.\" ============================================================================
.SH DESCRIPTION
.B wordcount
counts the words in its input and writes the total as a line of text to the
output.
A \(lqword\(rq is a maximal sequence of characters not containing a blank or tab
or newline.
.\" ============================================================================
.SH BUGS
The definition of \(lqword\(rq is simplistic.
.\" ============================================================================
.SH EXAMPLE
.RS 4
.nf
.B wordcount
.B A single line of input.
.B <ENDFILE>
5
.fi
.RE
.\" ============================================================================
